let a=document.getElementsByTagName("input")
let b=document.getElementsByClassName("again")
let c=document.getElementsByClassName("check")
let d=document.getElementsByClassName("score")
let e=document.getElementsByClassName("highscore")
console.log(a)
console.log(b)
console.log(c)
console.log(d)
console.log(e)
