###
get https://medium-api-psi.vercel.app/api/users


###
get https://medium-api-psi.vercel.app/api/users?id=63cde513f76277111603ecad



###
post https://medium-api-psi.vercel.app/api/users
content-type: application/json

{
  "username":"Oyuka",
  "password":"123123",
  "userType":"admin",
  "firstName": "Tom Frieden",
  "lastName": "Dr",
  "userId": "1",
  "userImg":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxy6RxLojUCau-I0PFwlyXWnb4zY2yq-dQyA&usqp=CAU",
  "organization": "Forbes"
}